export const prices = {
  tomatoBase: 10,
  cheeseBase: 10,
  garlicBase: 10,
  bbqBase: 10,
  chicken: 5,
  pepperoni: 10,
  ham: 5,
  beef: 7,
  bellPepper: 2,
  pineapple: 4,
  fetaCheese: 4,
  mushrooms: 3,
  sweetAndSourSauce: 2,
  teriyaki: 3,
  mustard: 1,
  thousandIslands: 1,
};
